export const AI_MODEL_CATALOG = {
  chatgpt: [
    "gpt-5.4-mini",
    "gpt-5.5",
    "gpt-5.4-nano",
    "gpt-5.6-luna",
    "gpt-5.6-sol",
    "gpt-5.6-terra",
    "gpt-4.1-nano",
    "gpt-5-mini",
    "gpt-4o-mini",
    "gpt-4o",
  ],
  gemini: [
    "gemini-2.5-flash",
    "gemini-3.6-flash",
    "gemini-3.5-flash",
    "gemini-3.1-pro",
    "gemini-3-flash-preview",
    "gemini-2.5-pro",
    "gemini-2.5-flash-lite",
    "gemini-flash-latest",
  ],
  claude: [
    "claude-sonnet-4-6",
    "claude-sonnet-5",
    "claude-opus-4-7",
    "claude-opus-4-8",
    "claude-opus-5",
  ],
  grok: [
    "grok-3",
    "grok-3-mini",
    "grok-4",
    "grok-4.5",
    "grok-4.3",
    "grok-4-fast-reasoning",
    "grok-4-fast-non-reasoning",
    "grok-4-20-reasoning",
    "grok-4-20-non-reasoning",
  ],
  deepseek: [
    "deepseek-chat",
    "deepseek-v3",
    "deepseek-v3.2",
    "deepseek-v3.1",
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "deepseek-r1",
    "deepseek-reasoner",
  ],
  qwen: [
    "qwen3.7-plus",
    "qwen3.7-max",
    "qwen3-coder",
    "qwen3-max",
    "qwen-plus",
    "qwen-turbo",
  ],
  kimi: [
    "kimi-k3",
    "kimi-k2.7-code",
    "kimi-k2.5",
    "kimi-k2",
  ],
  glm: [
    "glm-5.2",
    "glm-5.1",
    "glm-5",
    "glm-4.7",
    "glm-4.5",
  ],
  image: [
    "gpt-image-1",
    "gemini-2.5-flash-image",
    "gemini-3-pro-image",
    "grok-imagine-image",
  ],
};

export const getModelsByProvider = (provider) =>
  AI_MODEL_CATALOG[String(provider || "").trim().toLowerCase()] || [];

